export const paths = {
  index: "/",
  register: "/register",
  logout: "/",
  login: "/login",
  profile: "/profile",
  events: "/events",
  event: "/event/",
  newEvent: "/new/event",
  previousEvent: "/previous/",
  previousEvents: "/previous/events",
  locations: "/locations",
  location: "/location/",
  newLocation: "/new/location",
  guests: "/guests",
  contact: "/contact/",
  contacts: "/contacts",
  newContact: "/new/contact",
  feedback: "/feedback/",
  hungarian: "/hu-HU",
  newGuest: "/new/guest",
};
